### ISSUE TITLE
Create Wigglegrams using the photobooth-app - new Feature

### ISSUE THREAD

**Issue by mgineer85** [photobooth-app/photobooth-app#299]
### What are wigglegrams?

Wigglegrams are animated images that show a scene from multiple cameras perspectives at the same time (time-freeze-effect).

Find some here and there:
- https://www.reddit.com/r/wigglegrams/
- https://stereoscopy.blog/2020/06/21/making-wigglegrams-using-photoshop-tutorial/
- and many more, just google for wigglegrams...

### What does it need to create wigglegrams:
A setup with multiple cameras. A reference implementation is currently under development in a separate github repo: https://github.com/photobooth-app/wigglecam

##### In the Photobooth-App
- [x] Trigger HiRes, Receive HiRes and LoRes (stream)
- [x] Export gif/webp/avif
- [x] Basic calibration routine that gives stable results.
- [x] Improved documentation
- [x] Automated test coverage

 

##### In the Nodes (a node is one camera device)

- [x] HDR mode support
- [x] Skip frames in lores stream to save data/cpu
- [x] Master slave sync (picam native one) 
- [x] Install script (Ansible separate repo)
- [x] Docs, troubleshooting (Check if avail: nc -zv wiggle1 5550 5551 5552 )
- [x] Architecture description
- [x] BOM
- [ ] updated 3d printable case
- [x] setup guide 

#### Ideas for later releases, once the basic implementation stabilizes
- [ ] Gain/focus settings exchange so the cameras operate with the same parameters
- [x] Allow to calibrate for different charuco boards. (generation works, now just add the params to input of routine)
- [ ] Ensure trigger is sent to all cameras in a way that all deliver the same next frame. if trigger is right while a frame is generated, it could be the current one for 1 cam and the prev/next on another cam in rare cases.
- [ ] ...?

 

Find more information: https://github.com/photobooth-app/wigglecam

**Comment by PixelAlarm** [comment]
Really nice.
Would it be even possible to integrate more than 2 cameras? I saw an Event-booth with like 15 cameras and strong 3d-effect.
Synchronizing gphoto2-cams will be tough, I think.

In my opinion, it would be nice to add to a Photobooth. Would be really Special and an USP.

**Comment by mgineer85** [comment]
This made some progress recently. Unfortunately it's not a mobile camera any longer but shall be integrated in a bigger photobooth box. This way it's easier to tinker around with the hardware and can be shrunken later anyways once the software/components chosen stabilized and the concept has proven to work.

The basic idea is still the same but the tools changed to something more appropriate:
Pi Camera v3 -> Pi Zero 2 -> Ethernet Adapter -> Switch Port 1 \
Pi Camera v3 -> Pi Zero 2 -> Ethernet Adapter -> Switch Port 2  \ __--> Swich Port 5 -> Pi4/Pi5 hosting photobooth app
Pi Camera v3 -> Pi Zero 2 -> Ethernet Adapter -> Switch Port 3  /
Pi Camera v3 -> Pi Zero 2 -> Ethernet Adapter -> Switch Port 4 /

The app connects to the Pi Zeros via Network using pynng to transport messages. The messages are High resolution images, low resolution images (livestream) and trigger to capture.

## Todo

- [ ] Implement picamera2 synchronization (is available now natively in picamera2).
- [ ] Finish the mediaprocessing pipeline to consume 2...4 (or more) images from a camera array.
- [ ] Use HDR mode in picameras for better quality (resolution is sufficient for wigglegrams).
- [ ] Maybe add ansible scripts to maintain several devices easily.
- [ ] Add tests
  - [ ] for mediapipeline
  - [ ] for backend/pynng connector

## other refs

-> https://github.com/photobooth-app/photobooth-app/blob/main/src/photobooth/services/backends/wigglecam.py
-> https://github.com/photobooth-app/photobooth-app/blob/dev/src/photobooth/services/backends/wigglecam.py
-> https://github.com/photobooth-app/wigglecam

For a mobile camera, this one might be great, once sold: https://www.reddit.com/r/wigglegramProject/
